CSCI-GA-2820-FA24-003/wishlists

- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
Made the following changes in 
- Added create wishlist endpoint in routes.py
- Added test case for create wishlist test case
> Add create list

- service/__init__.py
- service/common/cli_commands.py
- service/common/error_handlers.py
- service/models/__init__.py
- service/models/items.py
- service/models/persistent_base.py
- service/models/wishlist.py
- service/routes.py
- tests/factories.py
- tests/test_items.py
- tests/test_routes.py
- tests/test_wishlist.py
1. Change Files Structure
2. Connect Wishlist Database with Item Database
3. Add Create new items test cases
4. Fix bugs in the section of "Create the wishlist" & "Creating items in the wishlists"
> Connect the Items Database with the Wishlist Database & Create New Items

- service/routes.py
- tests/test_items.py
- tests/test_routes.py
> Resolve delete items conflict

- service/models/wishlist.py
- service/routes.py
- tests/factories.py
- tests/test_routes.py
- tests/test_wishlist.py
* fix some basic linting error
* add test case for updating a wishlist by id, and two tests which should fail when there is no id and database error
* modify route.py and add test route
> add update a wishlist by id

- service/routes.py
- tests/test_items.py
- tests/test_routes.py
- tests/test_wishlist.py
Resolve the conflicts in deleting the wishlists branch
> Resolve delete wishlist conflicts

- service/routes.py
- tests/test_routes.py
- tests/test_wishlist.py
> Read the wishlist

- tests/test_items.py
- tests/test_routes.py
Added read an item 
- Added read an item test
- Added _create_items helper in 'test_routes.py'
> Added read an item 

- service/routes.py
- tests/test_items.py
- tests/test_routes.py
Modify route.py
Add test case for test_item.py
Add test case for test_routes.py and take some conditions that may fail into consideration in test case
> resolve the conflict with master

- tests/test_routes.py
added HTTP_415_UNSUPPORTED_MEDIA_TYPE test in 'test_routes.py'
> added-test-HTTP415

- README.md
Update the test coverage percentage to 84%
> Update test coverage percentage

- tests/test_items.py
- tests/test_wishlist.py
Added key_error and _error test
> added key_error and type_error

- service/models/items.py
- tests/factories.py
- tests/test_items.py
- tests/test_routes.py
- tests/test_wishlist.py
1. Add "category" attribute in the Items Database
2. Updated test cases and pass all the requirements
> Update "Category" Attribute in Items Database

- .github/workflows/ci.yml
Create a .github/workflows/ci.yml file and configure GitHub Actions to run your unit test cases every time someone pushes to the master branch or submits a Pull Request.
> Add CI workflow and Codecov

- service/models/items.py
- service/models/wishlist.py
- service/routes.py
- tests/factories.py
- tests/test_items.py
- tests/test_routes.py
- tests/test_wishlist.py
-Mark the Wishlists and the Items as favorites
-Add favorites attribute
-Add query by favorite
> Mark the wishlists and the items as favorites and add favorites attribute

- service/models/items.py
- service/models/wishlist.py
- service/routes.py
- tests/factories.py
- tests/test_items.py
- tests/test_routes.py
- tests/test_wishlist.py
change the route to fit for query string and added test for this
> add string query

- service/models/persistent_base.py
Fix the error to pass the CI testing
> Fix error in Linting to pass the CI test

- Dockerfile
- Makefile
- k8s/deployment.yaml
- k8s/ingress.yaml
- k8s/pv.yaml
- k8s/service.yaml
'#...' something need to be changed for PostgreSQL issue.
> add k8s folder

- service/static/index.html
1. Add Items Form in the user interface
2. Change the attributes for the tags
> Update UI in HTML

- service/static/index.html
- service/static/js/rest_api.js
1. Add create button for wishlist 
2. Add create button for item (the one for item occurs error because of bad setting of the route when querying wishlist with name -> still fixing)
> Add create button and function for wishlist

- service/static/index.html
- service/static/js/rest_api.js
Add functions in the update button
> Add update button functions

- service/static/js/rest_api.js
added delete wishlist and item function in ‘rest_api.js’
> added delete wishlist and item function

- Dockerfile
- poetry.lock
- pyproject.toml
The "behave" command can now work correctly
> Fix BDD Environment Setup Errors

- Dockerfile
- poetry.lock
- pyproject.toml
- service/models/items.py
- service/routes.py
- service/static/index.html
- service/static/js/rest_api.js
1. Add "query_all_items" function in (Using the route "/items" to make query for the attributes that matches the query)
2. Add new route "/items", so wishlist id is not required in this query URL 
3. Add "Query Items" button
> Enhance QUERY Items function

- service/routes.py
- service/static/js/rest_api.js
- tests/test_routes.py
merge two get method to one
add search ui function
> add-search-item-ui

- features/steps/web_steps.py
- features/steps/wishlists_steps.py
- features/wishlists.feature
- service/models/items.py
- service/static/index.html
- service/static/js/rest_api.js
-Add Read, Update, Delete, List, Query Feature for Wishlist
-modify the steps, index and rest_api.js
> Add Read, Update, Delete, List, Query Feature for Wishlist

- features/wishlists.feature
- service/routes.py
- service/static/js/rest_api.js
-Added query by name(wishlists) in tht 'route.py'
-Added Clear and List by Name Function for Wishlists
> Add Clear and List by Name Function for Wishlists

- features/wishlists.feature
- service/static/index.html
- service/static/js/rest_api.js
Solve the date conflict issues
Debug for bdd
Modify the .feature
> Solve the date conflict issues and debug for bdd

- output.txt
- service/models/items.py
> debug for items restful api

- service/__init__.py
- service/models/items.py
- service/routes.py
- tests/test_wishlist.py
-fix lint error
-remove unnecessary comment
> Improve lint and ready for pipeline build

- k8s/deployment.yaml
> change conf for webhook

- features/steps/wishlists_steps.py
- service/models/items.py
- service/routes.py
- service/static/index.html
- service/static/js/rest_api.js
add the completed item ui functions
debug for item.py and js and html
> add the completed item ui functions
